"""core ledger

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 21:23:25.054815

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_call_log')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_ai_call_log_created_at'), 'ai_call_log', ['created_at'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_ai_call_log_purpose'), 'ai_call_log', ['purpose'], unique=False, schema='personal_finances')
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_setting')),
    schema='personal_finances'
    )
    op.create_table('category_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hide_from_reports', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_group')),
    sa.UniqueConstraint('name', name=op.f('uq_category_group_name')),
    schema='personal_finances'
    )
    op.create_table('household_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_member')),
    sa.UniqueConstraint('name', name=op.f('uq_household_member_name')),
    schema='personal_finances'
    )
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institution')),
    sa.UniqueConstraint('name', name=op.f('uq_institution_name')),
    schema='personal_finances'
    )
    op.create_table('job',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_job_type'), 'job', ['type'], unique=False, schema='personal_finances')
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name')),
    schema='personal_finances'
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('mask', sa.String(length=10), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['personal_finances.institution.id'], name=op.f('fk_account_institution_id_institution'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account')),
    sa.UniqueConstraint('name', name=op.f('uq_account_name')),
    schema='personal_finances'
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('hide_from_reports', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['personal_finances.category_group.id'], name=op.f('fk_category_group_id_category_group'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('name', name=op.f('uq_category_name')),
    schema='personal_finances'
    )
    op.create_table('merchant_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('hits', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['personal_finances.category.id'], name=op.f('fk_merchant_rule_category_id_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_rule')),
    sa.UniqueConstraint('merchant', name=op.f('uq_merchant_rule_merchant')),
    schema='personal_finances'
    )
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_source', sa.String(length=20), nullable=True),
    sa.Column('suggested_category_id', sa.Integer(), nullable=True),
    sa.Column('suggestion_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('suggestion_reason', sa.Text(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('check_number', sa.String(length=30), nullable=True),
    sa.Column('source_type', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('budget_spread_months', sa.SmallInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['personal_finances.account.id'], name=op.f('fk_transaction_account_id_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['personal_finances.category.id'], name=op.f('fk_transaction_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['personal_finances.household_member.id'], name=op.f('fk_transaction_member_id_household_member'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_category_id'], ['personal_finances.category.id'], name=op.f('fk_transaction_suggested_category_id_category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction')),
    schema='personal_finances'
    )
    op.create_index('ix_transaction_account_date', 'transaction', ['account_id', 'txn_date'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_transaction_category_id'), 'transaction', ['category_id'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_transaction_external_id'), 'transaction', ['external_id'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_transaction_fingerprint'), 'transaction', ['fingerprint'], unique=False, schema='personal_finances')
    op.create_index('ix_transaction_live_date', 'transaction', ['txn_date'], unique=False, schema='personal_finances', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_transaction_merchant'), 'transaction', ['merchant'], unique=False, schema='personal_finances')
    op.create_table('transaction_tag',
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['personal_finances.tag.id'], name=op.f('fk_transaction_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['personal_finances.transaction.id'], name=op.f('fk_transaction_tag_transaction_id_transaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id', name=op.f('pk_transaction_tag')),
    schema='personal_finances'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_tag', schema='personal_finances')
    op.drop_index(op.f('ix_transaction_merchant'), table_name='transaction', schema='personal_finances')
    op.drop_index('ix_transaction_live_date', table_name='transaction', schema='personal_finances', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_transaction_fingerprint'), table_name='transaction', schema='personal_finances')
    op.drop_index(op.f('ix_transaction_external_id'), table_name='transaction', schema='personal_finances')
    op.drop_index(op.f('ix_transaction_category_id'), table_name='transaction', schema='personal_finances')
    op.drop_index('ix_transaction_account_date', table_name='transaction', schema='personal_finances')
    op.drop_table('transaction', schema='personal_finances')
    op.drop_table('merchant_rule', schema='personal_finances')
    op.drop_table('category', schema='personal_finances')
    op.drop_table('account', schema='personal_finances')
    op.drop_table('tag', schema='personal_finances')
    op.drop_index(op.f('ix_job_type'), table_name='job', schema='personal_finances')
    op.drop_index(op.f('ix_job_status'), table_name='job', schema='personal_finances')
    op.drop_table('job', schema='personal_finances')
    op.drop_table('institution', schema='personal_finances')
    op.drop_table('household_member', schema='personal_finances')
    op.drop_table('category_group', schema='personal_finances')
    op.drop_table('app_setting', schema='personal_finances')
    op.drop_index(op.f('ix_ai_call_log_purpose'), table_name='ai_call_log', schema='personal_finances')
    op.drop_index(op.f('ix_ai_call_log_created_at'), table_name='ai_call_log', schema='personal_finances')
    op.drop_table('ai_call_log', schema='personal_finances')
    # ### end Alembic commands ###
