"""imports and duplicates

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 05:56:35.973536

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # On Azure this must be allow-listed and pre-created by the admin (scripts/provision_azure_db.py).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA public")
    op.create_index('ix_transaction_amount_date', 'transaction', ['amount', 'txn_date'], unique=False,
                    schema='personal_finances', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='upload', nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment')),
    sa.UniqueConstraint('sha256', name=op.f('uq_attachment_sha256')),
    schema='personal_finances'
    )
    op.create_table('import_mapping_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('header_signature', sa.String(length=64), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('defaults', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_mapping_template')),
    sa.UniqueConstraint('header_signature', name=op.f('uq_import_mapping_template_header_signature')),
    schema='personal_finances'
    )
    op.create_table('import_batch',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('attachment_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), server_default='upload', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='mapping', nullable=False),
    sa.Column('sheet_name', sa.String(length=120), nullable=True),
    sa.Column('sheets', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('header_signature', sa.String(length=64), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('mapping_source', sa.String(length=20), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('defaults', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('doc_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['personal_finances.attachment.id'], name=op.f('fk_import_batch_attachment_id_attachment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['personal_finances.import_mapping_template.id'], name=op.f('fk_import_batch_template_id_import_mapping_template'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_import_batch_status'), 'import_batch', ['status'], unique=False, schema='personal_finances')
    op.create_table('category_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['personal_finances.category.id'], name=op.f('fk_category_alias_category_id_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_alias')),
    sa.UniqueConstraint('alias', name=op.f('uq_category_alias_alias')),
    schema='personal_finances'
    )
    op.create_table('import_row',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_hint', sa.String(length=200), nullable=True),
    sa.Column('account_hint', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('check_number', sa.String(length=30), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('decision', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['personal_finances.account.id'], name=op.f('fk_import_row_account_id_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['personal_finances.import_batch.id'], name=op.f('fk_import_row_batch_id_import_batch'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['personal_finances.category.id'], name=op.f('fk_import_row_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['personal_finances.transaction.id'], name=op.f('fk_import_row_transaction_id_transaction'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_row')),
    schema='personal_finances'
    )
    op.create_index('ix_import_row_batch_idx', 'import_row', ['batch_id', 'row_index'], unique=False, schema='personal_finances')
    op.create_table('duplicate_pair',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('txn_a_id', sa.BigInteger(), nullable=False),
    sa.Column('txn_b_id', sa.BigInteger(), nullable=True),
    sa.Column('import_row_id', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('ai_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=25), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['import_row_id'], ['personal_finances.import_row.id'], name=op.f('fk_duplicate_pair_import_row_id_import_row'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['txn_a_id'], ['personal_finances.transaction.id'], name=op.f('fk_duplicate_pair_txn_a_id_transaction'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['txn_b_id'], ['personal_finances.transaction.id'], name=op.f('fk_duplicate_pair_txn_b_id_transaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_pair')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_duplicate_pair_status'), 'duplicate_pair', ['status'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_duplicate_pair_txn_a_id'), 'duplicate_pair', ['txn_a_id'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_duplicate_pair_txn_b_id'), 'duplicate_pair', ['txn_b_id'], unique=False, schema='personal_finances')
    op.create_index('uq_duplicate_pair_row', 'duplicate_pair', ['import_row_id', 'txn_a_id'], unique=True, schema='personal_finances', postgresql_where=sa.text('import_row_id IS NOT NULL'))
    op.create_index('uq_duplicate_pair_txns', 'duplicate_pair', ['txn_a_id', 'txn_b_id'], unique=True, schema='personal_finances', postgresql_where=sa.text('txn_b_id IS NOT NULL'))
    op.add_column('transaction', sa.Column('import_batch_id', sa.BigInteger(), nullable=True), schema='personal_finances')
    op.create_index(op.f('ix_transaction_import_batch_id'), 'transaction', ['import_batch_id'], unique=False, schema='personal_finances')
    op.create_foreign_key(op.f('fk_transaction_import_batch_id_import_batch'), 'transaction', 'import_batch', ['import_batch_id'], ['id'], source_schema='personal_finances', referent_schema='personal_finances', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transaction_import_batch_id_import_batch'), 'transaction', schema='personal_finances', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_import_batch_id'), table_name='transaction', schema='personal_finances')
    op.drop_column('transaction', 'import_batch_id', schema='personal_finances')
    op.drop_index('uq_duplicate_pair_txns', table_name='duplicate_pair', schema='personal_finances', postgresql_where=sa.text('txn_b_id IS NOT NULL'))
    op.drop_index('uq_duplicate_pair_row', table_name='duplicate_pair', schema='personal_finances', postgresql_where=sa.text('import_row_id IS NOT NULL'))
    op.drop_index(op.f('ix_duplicate_pair_txn_b_id'), table_name='duplicate_pair', schema='personal_finances')
    op.drop_index(op.f('ix_duplicate_pair_txn_a_id'), table_name='duplicate_pair', schema='personal_finances')
    op.drop_index(op.f('ix_duplicate_pair_status'), table_name='duplicate_pair', schema='personal_finances')
    op.drop_table('duplicate_pair', schema='personal_finances')
    op.drop_index('ix_import_row_batch_idx', table_name='import_row', schema='personal_finances')
    op.drop_table('import_row', schema='personal_finances')
    op.drop_table('category_alias', schema='personal_finances')
    op.drop_index(op.f('ix_import_batch_status'), table_name='import_batch', schema='personal_finances')
    op.drop_table('import_batch', schema='personal_finances')
    op.drop_table('import_mapping_template', schema='personal_finances')
    op.drop_table('attachment', schema='personal_finances')
    op.drop_index('ix_transaction_amount_date', table_name='transaction', schema='personal_finances')
    # ### end Alembic commands ###
