"""statements

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-29 17:05:53.839621

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('service_type', sa.String(length=60), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('primary_metric', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['personal_finances.category.id'], name=op.f('fk_statement_series_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['personal_finances.tag.id'], name=op.f('fk_statement_series_tag_id_tag'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement_series')),
    sa.UniqueConstraint('name', name=op.f('uq_statement_series_name')),
    schema='personal_finances'
    )
    op.create_table('statement',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='processing', nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('account_ref', sa.String(length=40), nullable=True),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestion', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['personal_finances.attachment.id'], name=op.f('fk_statement_attachment_id_attachment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['series_id'], ['personal_finances.statement_series.id'], name=op.f('fk_statement_series_id_statement_series'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_statement_attachment_id'), 'statement', ['attachment_id'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_statement_series_id'), 'statement', ['series_id'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_statement_status'), 'statement', ['status'], unique=False, schema='personal_finances')
    op.create_table('statement_transaction',
    sa.Column('statement_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['personal_finances.statement.id'], name=op.f('fk_statement_transaction_statement_id_statement'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['personal_finances.transaction.id'], name=op.f('fk_statement_transaction_transaction_id_transaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('statement_id', 'transaction_id', name=op.f('pk_statement_transaction')),
    schema='personal_finances'
    )
    op.create_table('statement_usage',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('statement_id', sa.BigInteger(), nullable=False),
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['personal_finances.statement.id'], name=op.f('fk_statement_usage_statement_id_statement'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement_usage')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_statement_usage_statement_id'), 'statement_usage', ['statement_id'], unique=False, schema='personal_finances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statement_usage_statement_id'), table_name='statement_usage', schema='personal_finances')
    op.drop_table('statement_usage', schema='personal_finances')
    op.drop_table('statement_transaction', schema='personal_finances')
    op.drop_index(op.f('ix_statement_status'), table_name='statement', schema='personal_finances')
    op.drop_index(op.f('ix_statement_series_id'), table_name='statement', schema='personal_finances')
    op.drop_index(op.f('ix_statement_attachment_id'), table_name='statement', schema='personal_finances')
    op.drop_table('statement', schema='personal_finances')
    op.drop_table('statement_series', schema='personal_finances')
    # ### end Alembic commands ###
