"""budgets

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-29 17:14:01.689134

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period_type IN ('month', 'quarter', 'year')", name=op.f('ck_budget_period_type')),
    sa.CheckConstraint('(category_id IS NULL) <> (group_id IS NULL)', name=op.f('ck_budget_one_target')),
    sa.ForeignKeyConstraint(['category_id'], ['personal_finances.category.id'], name=op.f('fk_budget_category_id_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['personal_finances.category_group.id'], name=op.f('fk_budget_group_id_category_group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget')),
    sa.UniqueConstraint('category_id', name=op.f('uq_budget_category_id')),
    sa.UniqueConstraint('group_id', name=op.f('uq_budget_group_id')),
    schema='personal_finances'
    )
    op.create_table('spread_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('merchant_pattern', sa.String(length=200), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('months', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('months BETWEEN 1 AND 60', name=op.f('ck_spread_rule_months')),
    sa.ForeignKeyConstraint(['category_id'], ['personal_finances.category.id'], name=op.f('fk_spread_rule_category_id_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spread_rule')),
    schema='personal_finances'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spread_rule', schema='personal_finances')
    op.drop_table('budget', schema='personal_finances')
    # ### end Alembic commands ###
