"""anomalies

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-29 17:24:42.103896

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('subject_key', sa.String(length=120), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('baseline', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ai_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['personal_finances.category.id'], name=op.f('fk_anomaly_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['personal_finances.statement_series.id'], name=op.f('fk_anomaly_series_id_statement_series'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['personal_finances.transaction.id'], name=op.f('fk_anomaly_transaction_id_transaction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomaly')),
    sa.UniqueConstraint('subject_key', name=op.f('uq_anomaly_subject_key')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_anomaly_kind'), 'anomaly', ['kind'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_anomaly_period'), 'anomaly', ['period'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_anomaly_status'), 'anomaly', ['status'], unique=False, schema='personal_finances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_status'), table_name='anomaly', schema='personal_finances')
    op.drop_index(op.f('ix_anomaly_period'), table_name='anomaly', schema='personal_finances')
    op.drop_index(op.f('ix_anomaly_kind'), table_name='anomaly', schema='personal_finances')
    op.drop_table('anomaly', schema='personal_finances')
    # ### end Alembic commands ###
