"""chat

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29 17:36:30.328007

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_session')),
    schema='personal_finances'
    )
    op.create_table('chat_message',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_id', sa.BigInteger(), nullable=True),
    sa.Column('queries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['personal_finances.attachment.id'], name=op.f('fk_chat_message_attachment_id_attachment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['personal_finances.chat_session.id'], name=op.f('fk_chat_message_session_id_chat_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False, schema='personal_finances')
    # ### end Alembic commands ###
    # On Azure the role is pre-created by the admin (the app principal cannot create roles).
    op.execute(
        """
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pf_readonly') THEN
                CREATE ROLE pf_readonly NOLOGIN;
            END IF;
        END $$;
        """
    )
    for name, sql in VIEWS.items():
        op.execute(f"CREATE OR REPLACE VIEW personal_finances.{name} AS {sql}")
        op.execute(f"GRANT SELECT ON personal_finances.{name} TO pf_readonly")
    op.execute("GRANT USAGE ON SCHEMA personal_finances TO pf_readonly")


S = "personal_finances"
VIEWS = {
    "v_transactions": f"""
        SELECT t.id, t.txn_date AS date, t.posted_date, t.description, t.merchant, t.amount,
               c.name AS category, g.name AS category_group, c.type AS category_type,
               coalesce(c.hide_from_reports OR g.hide_from_reports, false) AS hidden_from_reports,
               a.name AS account, a.account_type, i.name AS institution, m.name AS member,
               ARRAY(SELECT tg.name FROM {S}.transaction_tag tt JOIN {S}.tag tg ON tg.id = tt.tag_id
                     WHERE tt.transaction_id = t.id ORDER BY tg.name) AS tags,
               t.notes, t.source_type AS source, t.budget_spread_months, CAST(t.created_at AS date) AS date_added,
               EXISTS (SELECT 1 FROM {S}.statement_transaction st WHERE st.transaction_id = t.id) AS has_statement
        FROM {S}.transaction t
        LEFT JOIN {S}.category c ON c.id = t.category_id
        LEFT JOIN {S}.category_group g ON g.id = c.group_id
        LEFT JOIN {S}.account a ON a.id = t.account_id
        LEFT JOIN {S}.institution i ON i.id = a.institution_id
        LEFT JOIN {S}.household_member m ON m.id = t.member_id
        WHERE t.deleted_at IS NULL""",
    "v_categories": f"""
        SELECT c.name AS category, g.name AS category_group, c.type,
               (c.hide_from_reports OR g.hide_from_reports) AS hidden_from_reports, c.is_active
        FROM {S}.category c JOIN {S}.category_group g ON g.id = c.group_id""",
    "v_accounts": f"""
        SELECT a.name AS account, a.account_type, i.name AS institution, a.mask, a.is_closed, a.is_hidden
        FROM {S}.account a LEFT JOIN {S}.institution i ON i.id = a.institution_id""",
    "v_statements": f"""
        SELECT s.id, sr.name AS series, s.vendor, s.document_type, s.status, s.statement_date, s.period_start,
               s.period_end, s.due_date, s.amount_due, s.summary,
               u.metric AS usage_metric, u.value AS usage_value, u.unit AS usage_unit,
               ARRAY(SELECT x.transaction_id FROM {S}.statement_transaction x WHERE x.statement_id = s.id)
                   AS linked_transaction_ids
        FROM {S}.statement s
        LEFT JOIN {S}.statement_series sr ON sr.id = s.series_id
        LEFT JOIN LATERAL (
            SELECT * FROM {S}.statement_usage su WHERE su.statement_id = s.id ORDER BY su.is_primary DESC, su.id LIMIT 1
        ) u ON true
        WHERE s.status IN ('approved', 'suggested')""",
    "v_statement_usage": f"""
        SELECT s.id AS statement_id, sr.name AS series, s.period_start, s.period_end, s.statement_date,
               su.metric, su.value, su.unit, su.is_primary
        FROM {S}.statement_usage su
        JOIN {S}.statement s ON s.id = su.statement_id
        LEFT JOIN {S}.statement_series sr ON sr.id = s.series_id
        WHERE s.status = 'approved'""",
    "v_budgets": f"""
        SELECT coalesce(c.name, g.name) AS target, CASE WHEN b.category_id IS NULL THEN 'group' ELSE 'category' END
                   AS target_type, b.period_type, b.amount, b.notes
        FROM {S}.budget b
        LEFT JOIN {S}.category c ON c.id = b.category_id
        LEFT JOIN {S}.category_group g ON g.id = b.group_id""",
    "v_monthly_category": f"""
        SELECT CAST(date_trunc('month', t.txn_date) AS date) AS month, c.name AS category,
               g.name AS category_group, c.type AS category_type,
               coalesce(c.hide_from_reports OR g.hide_from_reports, false) AS hidden_from_reports,
               sum(t.amount) AS net_amount, count(*) AS transactions
        FROM {S}.transaction t
        LEFT JOIN {S}.category c ON c.id = t.category_id
        LEFT JOIN {S}.category_group g ON g.id = c.group_id
        WHERE t.deleted_at IS NULL
        GROUP BY 1, 2, 3, 4, 5""",
}


def downgrade() -> None:
    for name in VIEWS:
        op.execute(f"DROP VIEW IF EXISTS personal_finances.{name}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message', schema='personal_finances')
    op.drop_table('chat_message', schema='personal_finances')
    op.drop_table('chat_session', schema='personal_finances')
    # ### end Alembic commands ###
