"""alerts

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-29 17:49:37.134074

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_event',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('subject_key', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_event')),
    sa.UniqueConstraint('subject_key', name=op.f('uq_alert_event_subject_key')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_alert_event_kind'), 'alert_event', ['kind'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_alert_event_status'), 'alert_event', ['status'], unique=False, schema='personal_finances')
    op.create_table('alert_recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_recipient')),
    sa.UniqueConstraint('email', name=op.f('uq_alert_recipient_email')),
    schema='personal_finances'
    )
    op.create_table('alert_rule',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('kind', name=op.f('pk_alert_rule')),
    schema='personal_finances'
    )
    # ### end Alembic commands ###
    op.execute(
        """
        INSERT INTO personal_finances.alert_rule (kind, enabled, params) VALUES
            ('budget_overspend', true, '{"pace": true}'),
            ('out_of_norm', true, '{}'),
            ('large_transaction', false, '{"threshold": 500}'),
            ('weekly_digest', true, '{}')
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_rule', schema='personal_finances')
    op.drop_table('alert_recipient', schema='personal_finances')
    op.drop_index(op.f('ix_alert_event_status'), table_name='alert_event', schema='personal_finances')
    op.drop_index(op.f('ix_alert_event_kind'), table_name='alert_event', schema='personal_finances')
    op.drop_table('alert_event', schema='personal_finances')
    # ### end Alembic commands ###
