"""sources

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-29 18:01:15.293291

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('secret', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source')),
    sa.UniqueConstraint('kind', name=op.f('uq_source_kind')),
    schema='personal_finances'
    )
    op.create_table('account_balance',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('available', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['personal_finances.account.id'], name=op.f('fk_account_balance_account_id_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_balance')),
    sa.UniqueConstraint('account_id', 'as_of', 'source', name=op.f('uq_account_balance_account_id_as_of_source')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_account_balance_account_id'), 'account_balance', ['account_id'], unique=False, schema='personal_finances')
    op.create_table('holding',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('shares', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['personal_finances.account.id'], name=op.f('fk_holding_account_id_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holding')),
    sa.UniqueConstraint('account_id', 'as_of', 'external_id', name=op.f('uq_holding_account_id_as_of_external_id')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_holding_account_id'), 'holding', ['account_id'], unique=False, schema='personal_finances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holding_account_id'), table_name='holding', schema='personal_finances')
    op.drop_table('holding', schema='personal_finances')
    op.drop_index(op.f('ix_account_balance_account_id'), table_name='account_balance', schema='personal_finances')
    op.drop_table('account_balance', schema='personal_finances')
    op.drop_table('source', schema='personal_finances')
    # ### end Alembic commands ###
