"""backfill

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-29 18:20:31.011016

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0011'
down_revision: str | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_file',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('provider', sa.String(length=10), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attachment_id', sa.BigInteger(), nullable=True),
    sa.Column('import_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('statement_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['personal_finances.attachment.id'], name=op.f('fk_backfill_file_attachment_id_attachment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['personal_finances.import_batch.id'], name=op.f('fk_backfill_file_import_batch_id_import_batch'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['personal_finances.statement.id'], name=op.f('fk_backfill_file_statement_id_statement'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backfill_file')),
    sa.UniqueConstraint('provider', 'external_id', name=op.f('uq_backfill_file_provider_external_id')),
    schema='personal_finances'
    )
    op.create_index(op.f('ix_backfill_file_kind'), 'backfill_file', ['kind'], unique=False, schema='personal_finances')
    op.create_index(op.f('ix_backfill_file_status'), 'backfill_file', ['status'], unique=False, schema='personal_finances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backfill_file_status'), table_name='backfill_file', schema='personal_finances')
    op.drop_index(op.f('ix_backfill_file_kind'), table_name='backfill_file', schema='personal_finances')
    op.drop_table('backfill_file', schema='personal_finances')
    # ### end Alembic commands ###
